# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: gromit.tenancy::lang.controllers.tenants.config.form.name

# Model Form Field configuration
form: $/gromit/tenancy/models/tenant/fields.yaml

# Model Class name
modelClass: GromIT\Tenancy\Models\Tenant

# Default redirect location
defaultRedirect: gromit/tenancy/tenants

# Create page
create:
    title: gromit.tenancy::lang.controllers.tenants.config.form.create.title
    redirect: gromit/tenancy/tenants/update/:id
    redirectClose: gromit/tenancy/tenants
    flashSaved: gromit.tenancy::lang.controllers.tenants.config.form.create.flashSaved

# Update page
update:
    title: gromit.tenancy::lang.controllers.tenants.config.form.update.title
    redirect: gromit/tenancy/tenants
    redirectClose: gromit/tenancy/tenants
    flashSaved: gromit.tenancy::lang.controllers.tenants.config.form.update.flashSaved
    flashDeleted: gromit.tenancy::lang.controllers.tenants.config.form.update.flashDeleted

# Preview page
preview:
    title: gromit.tenancy::lang.controllers.tenants.config.form.preview.title
