# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/sergeykasyanov/tenancy/models/tenant/columns.yaml

# Model Class name
modelClass: SergeyKasyanov\Tenancy\Models\Tenant

# List Title
title: sergeykasyanov.tenancy::lang.controllers.tenants.config.list.title

# Link URL for each record
recordUrl: sergeykasyanov/tenancy/tenants/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: partials/list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
