domains:
    label: sergeykasyanov.tenancy::lang.controllers.tenants.config.relation.domains.label
    view:
        list: $/sergeykasyanov/tenancy/models/domain/columns.yaml
        toolbarButtons:
            create: sergeykasyanov.tenancy::lang.controllers.tenants.config.relation.domains.view.toolbarButtons.create
            delete: sergeykasyanov.tenancy::lang.controllers.tenants.config.relation.domains.view.toolbarButtons.delete
    manage:
        form: $/sergeykasyanov/tenancy/models/domain/fields.yaml